/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sdd_client_myjnitest_jni_MyJNIUtil */

#ifndef _Included_com_sdd_client_myjnitest_jni_MyJNIUtil
#define _Included_com_sdd_client_myjnitest_jni_MyJNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sdd_client_myjnitest_jni_MyJNIUtil
 * Method:    getMyName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sdd_client_myjnitest_jni_MyJNIUtil_getMyName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
